#!/usr/bin/bash


# Install Programs
echo "\n~Installing Programs~"
sudo pacman -S neofetch neovim zsh --noconfirm


# Install SpaceVim (via https://spacevim.org/quick-start-guide/)
echo "\n~Installing SpaceVim~"
curl -sLf https://spacevim.org/install.sh | bash


# Install Oh-My-Zsh (https://github.com/robbyrussell/oh-my-zsh/)
echo "\n~Installing Oh My Zsh~"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
export ZSH_CUSTOM=~/.oh-my-zsh/custom

# Install extra Zsh plugins
echo "\n~Installing Oh My Zsh Extras"

# Spaceship Prompt
git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt"

ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"

# zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# zsh-history-subsearch-search
git clone https://github.com/zsh-users/zsh-history-substring-search ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search

# Refresh changes
source ~/.zshrc
