#!/usr/bin/bash


# Install Programs
echo "~Installing Programs~"
sudo pacman -S --needed curl git lsd mosh neofetch neovim python python-black python-neovim python-pip tmux zathura zathura-cb zathura-pdf-mupdf zathura-ps zsh --noconfirm

# Install yay for the AUR
echo "~Installing yay~"
git clone https://aur.archlinux.org/yay.git
cd yay/
makepkg -si
cd ..
rm -rf yay/

# Install SpaceVim (via https://spacevim.org/quick-start-guide/)
echo "~Installing SpaceVim~"
curl -sLf https://spacevim.org/install.sh | bash


# Setup package manager for for tmux
echo "~Installing tpm~"
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm


# Install Oh-My-Zsh (https://github.com/robbyrussell/oh-my-zsh/)
echo "~Installing Oh My Zsh~"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
export ZSH_CUSTOM=~/.oh-my-zsh/custom

# Install extra Zsh plugins
echo "~Installing Oh My Zsh Extras"

# Spaceship Prompt
git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt"

ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"

# zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# zsh-history-subsearch-search
git clone https://github.com/zsh-users/zsh-history-substring-search ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search

# yadm-zsh
git clone https://github.com/juanrgon/yadm-zsh ${ZSH_CUSTOM:-~/.oh-my-zsh/custom/}/plugins/yadm-zsh

# Reclaiming our zsh config
echo "~Setting backup as main config~"
mv ~/.zshrc.pre-oh-my-zsh ~/.zshrc

# Set zsh as main shell
echo "~Setting ZSH as user shell~"
chsh -s /usr/bin/zsh

# Refresh changes
source ~/.zshrc
